spring.datasource.url=jdbc:postgresql://localhost:5432/retention
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=backend

spring.config.import=optional:application-local.properties
gemini.api.key=${GEMINI_API_KEY:}
gupshup.api.key=${GUPSHUP_API_KEY:}
gupshup.sender.number=${GUPSHUP_SENDER_NUMBER:}
